services:
  devrunner:
    image: devrunner
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        - USER_UID=${USER_UID}
    volumes:
      - type: bind
        source: ./
        target: /home/devrunner/src
    restart: unless-stopped
    network_mode: host

